### ISSUE TITLE
[Discussion] To-do list of Apache Incubator application

### ISSUE THREAD

**Issue by acezen** [alibaba/GraphAr#274]
We prepare to  contribute/transfer GraphAr project to Apache Incubator. And Apache has an [official process](https://incubator.apache.org/cookbook/) to apply for Apache Incubator. Here we list some items to do before we submit the proposal to Apache Incubator

- [x] License in compliance with requirements （include dependencies)
- [ ] Incubator proposal and refinement of the project
    - [x] Draft
    - [x] Dependencies license check.
    - [x] Put incubator proposal to discussion.
    - [x] English document.
    - [x] Full-fill the issue description and the road map.
    - [x] SGA/LCA check.
- [x]  Confirm the core developer and initial committers.
    - [x] initial committer team 
- [x] Look for champion and incubation mentors
- [x] Discussion in apache incubator mail list (plan to submit at Wednesday，02.27)
- [x] CCLA, SGA and ICLA prepare.

Any comments, questions, and suggestions from both the end-users as well as developers are highly appreciated!

**Comment by acezen** [comment]
Done since our proposal has been accepted. https://lists.apache.org/thread/4d49g4s96fpmnq7csbyg2lhq5939tnqf
